import React,{useEffect,useRef,useState} from "react";
export function MatchedComparison({root,evaluators=[]}) {
  const [models,setModels]=useState([]),[left,setLeft]=useState(""),[right,setRight]=useState(""),[evaluator,setEvaluator]=useState(""),[result,setResult]=useState(null),[error,setError]=useState(null);
  const requestEpoch=useRef(0);
  const evaluatorAvailable=evaluators.some(e=>e.fingerprint===evaluator);
  useEffect(()=>{if(evaluator && !evaluatorAvailable){requestEpoch.current++;setEvaluator("");setResult(null);setError(null);}},[evaluator,evaluatorAvailable]);
  useEffect(()=>{let current=true;requestEpoch.current++;setResult(null);setModels([]);setError(null);fetch(`${root}/api/compare/matched`,{credentials:"same-origin"}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);return d;}).then(d=>{if(current)setModels(d.models || []);}).catch(e=>{if(current)setError(String(e));});return()=>{current=false;requestEpoch.current++;};},[root]);
  const change=(setter,value)=>{requestEpoch.current++;setter(value);setResult(null);setError(null);};
  async function compare() {
    const epoch=++requestEpoch.current;
    setResult(null);setError(null);
    try {const r=await fetch(`${root}/api/compare/matched?${new URLSearchParams({left,right,evaluator})}`,{credentials:"same-origin"});const d=await r.json();if(!r.ok)throw Error(d.error);if(epoch===requestEpoch.current){setResult(d);setError(null);}}catch(e){if(epoch===requestEpoch.current)setError(String(e));}
  }
  return <section className="border p-5 space-y-3" style={{borderColor:"#26332e",background:"#111715"}}><h2 className="font-semibold">Compare replies on matched inputs</h2><p className="text-sm" style={{color:"#94a39d"}}>Use the same captured prompt and conversation context, with one judge version. Repeated input and extra replies from the same conversation are excluded. This does not replay a whole conversation.</p><div className="grid sm:grid-cols-3 gap-3">{[["Base model",left,setLeft],["Other model",right,setRight]].map(([label,value,set])=><label key={label} className="text-sm">{label}<select className="block w-full border p-2 mt-1 bg-transparent" value={value} onChange={e=>change(set,e.target.value)}><option value="">Select model</option>{models.map(m=><option key={m}>{m}</option>)}</select></label>)}<label className="text-sm">Judge version<select className="block w-full border p-2 mt-1 bg-transparent" value={evaluator} onChange={e=>change(setEvaluator,e.target.value)}><option value="">Select evaluator</option>{evaluators.map(e=><option value={e.fingerprint} key={e.fingerprint}>{e.label || e.fingerprint.slice(0,12)}</option>)}</select></label></div><button disabled={!left || !right || left===right || !evaluator} className="border p-2 text-sm" onClick={compare}>Compare saved matched replies</button>{result && <div className="text-sm space-y-2"><p>Captured {result.coverage.captured} → matched input pairs {result.coverage.matchedInputs} · missing input {result.coverage.missingInput} · repeated input {result.coverage.repeatedInput} · repeated conversation {result.coverage.excludedRepeatedConversation}</p>{result.metrics.map(m=><div key={m.dimension} className="border p-3" style={{borderColor:"#26332e"}}>{m.dimension} · {m.leftPassRate==null ? "No comparable judgment" : `${(100*m.leftPassRate).toFixed(1)}% → ${(100*m.rightPassRate).toFixed(1)}% · paired n ${m.pairedEvaluable}`}<div className="text-xs mt-1" style={{color:"#94a39d"}}>Missing {m.missing} · unclear {m.unclear} · judge errors {m.error}{m.leftCI && ` · 95% rate intervals ${(100*m.leftCI[0]).toFixed(1)}–${(100*m.leftCI[1]).toFixed(1)}% / ${(100*m.rightCI[0]).toFixed(1)}–${(100*m.rightCI[1]).toFixed(1)}%`}</div></div>)}<p style={{color:"#94a39d"}}>{result.limitation}</p></div>}{error && <p role="alert" style={{color:"#ff6b6b"}}>{error}</p>}</section>;
}
